server:
  port: 9999
config:
  user: User Hello Dev from cloud config server
  role: -role is Development from cloud server
charge:
  authority:
    - read
    - write

management.endpoints.web.exposure.include: "*"   
spring.cloud.config.uri: https://github.com/shubhamsadare/ConfigRepo.git

#Disable security of the Management endpoint
management:
  security:
    enabled: false
