spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:shubhamsadare/ConfigRepo.git
          default-label: main
          clone-on-start: true
        bootstrap: true
      enabled: true
   
  application:
    name: Config-Server
server:
  port: 9999
